CREATE TABLE `kaileshi_no_source_refund_order_align_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `refund_id` varchar(255) DEFAULT NULL,
  `out_refund_id` varchar(255) DEFAULT NULL,
  `node_kdt_id` bigint(20) DEFAULT NULL,
  `yz_shop_no` varchar(255) DEFAULT NULL,
  `out_shop_no` varchar(255) DEFAULT NULL,
  `shop_result` varchar(255) DEFAULT NULL,
  `yz_refund_fee` bigint(20) DEFAULT NULL,
  `out_refund_fee` bigint(20) DEFAULT NULL,
  `refund_fee_result` varchar(255) DEFAULT NULL,
  `user_id` varchar(255) DEFAULT NULL,
  `yz_member_id` varchar(255) DEFAULT NULL,
  `out_open_id` varchar(255) DEFAULT NULL,
  `customer_no` varchar(255) DEFAULT NULL,
  `out_member_id` varchar(255) DEFAULT NULL,
  `member_id_result` varchar(255) DEFAULT NULL,
  `is_mock_item_id` varchar(255) DEFAULT NULL,
  `sub_order_result` varchar(255) DEFAULT NULL,
  `sub_order_fail_reason` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_refund` (`app_id`,`refund_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kaileshi_order_align` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `tid` varchar(255) DEFAULT NULL,
  `out_tid` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_out_tid` (`app_id`,`out_tid`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kaileshi_order_align_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `tid` varchar(255) DEFAULT NULL,
  `out_tid` varchar(255) DEFAULT NULL,
  `yz_create_time` varchar(255) DEFAULT NULL,
  `out_create_time` varchar(255) DEFAULT NULL,
  `create_time_result` varchar(255) DEFAULT NULL,
  `yz_pay_time` varchar(255) DEFAULT NULL,
  `out_pay_time` varchar(255) DEFAULT NULL,
  `pay_time_result` varchar(255) DEFAULT NULL,
  `node_kdt_id` bigint(20) DEFAULT NULL,
  `yz_shop_no` varchar(255) DEFAULT NULL,
  `out_shop_no` varchar(255) DEFAULT NULL,
  `shop_result` varchar(255) DEFAULT NULL,
  `yz_total_amount` bigint(20) DEFAULT NULL,
  `out_total_amount` bigint(20) DEFAULT NULL,
  `total_amount_result` varchar(255) DEFAULT NULL,
  `yz_discount_amount` bigint(20) DEFAULT NULL,
  `out_discount_amount` bigint(20) DEFAULT NULL,
  `discount_amount_result` varchar(255) DEFAULT NULL,
  `yz_payment` bigint(20) DEFAULT NULL,
  `out_payment` bigint(20) DEFAULT NULL,
  `payment_result` varchar(255) DEFAULT NULL,
  `yz_member_id` varchar(255) DEFAULT NULL,
  `out_open_id` varchar(255) DEFAULT NULL,
  `out_member_id` varchar(255) DEFAULT NULL,
  `customer_no` varchar(255) DEFAULT NULL,
  `member_id_result` varchar(255) DEFAULT NULL,
  `yz_channel` varchar(255) DEFAULT NULL,
  `out_channel` varchar(255) DEFAULT NULL,
  `channel_result` varchar(255) DEFAULT NULL,
  `is_mock_item_id` varchar(255) DEFAULT NULL,
  `sub_order_result` varchar(255) DEFAULT NULL,
  `sub_order_fail_reason` text,
  `yz_guide_no_list` varchar(255) DEFAULT NULL,
  `out_guide_no_list` varchar(255) DEFAULT NULL,
  `item_guide_result` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_tid` (`app_id`,`tid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kaileshi_order_refund_align` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `refund_id` varchar(255) DEFAULT NULL,
  `out_refund_id` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `is_no_source_refund_order` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_out_refund` (`app_id`,`out_refund_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kaileshi_refund_order_align_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `refund_id` varchar(255) DEFAULT NULL,
  `out_refund_id` varchar(255) DEFAULT NULL,
  `yz_create_time` varchar(255) DEFAULT NULL,
  `out_create_time` varchar(255) DEFAULT NULL,
  `create_time_result` varchar(255) DEFAULT NULL,
  `node_kdt_id` bigint(20) DEFAULT NULL,
  `yz_shop_no` varchar(255) DEFAULT NULL,
  `out_shop_no` varchar(255) DEFAULT NULL,
  `shop_result` varchar(255) DEFAULT NULL,
  `yz_payment` bigint(20) DEFAULT NULL,
  `out_payment` bigint(20) DEFAULT NULL,
  `payment_result` varchar(255) DEFAULT NULL,
  `sub_order_result` varchar(255) DEFAULT NULL,
  `sub_order_fail_reason` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_refund` (`app_id`,`refund_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kls_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `yz_open_id` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `out_open_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_yz_open_id` (`yz_open_id`),
  KEY `idx_out_open_id` (`out_open_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `third_party_order_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `out_tid` varchar(255) DEFAULT NULL,
  `out_tid_detail` text,
  `status` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_out_tid` (`app_id`,`out_tid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `youzan_order_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `tid` varchar(255) DEFAULT NULL,
  `tid_detail` text,
  `status` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_tid` (`app_id`,`tid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kls_member_align` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `yz_open_id` varchar(255) DEFAULT NULL,
  `member_id` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_mobile` (`app_id`,`mobile`),
  KEY `idx_app_yz_open_id` (`app_id`,`yz_open_id`),
  KEY `idx_app_member_id` (`app_id`,`member_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `kai_le_shi_member_align_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `yz_open_id` varchar(255) DEFAULT NULL,
  `member_id` varchar(255) DEFAULT NULL,
  `yz_name` varchar(255) DEFAULT NULL,
  `out_name` varchar(255) DEFAULT NULL,
  `name_result` varchar(255) DEFAULT NULL,
  `yz_gender` int(11) DEFAULT NULL,
  `out_gender` varchar(255) DEFAULT NULL,
  `gender_result` varchar(255) DEFAULT NULL,
  `yz_birthday` varchar(255) DEFAULT NULL,
  `out_birthday` varchar(255) DEFAULT NULL,
  `birthday_result` varchar(255) DEFAULT NULL,
  `yz_customer_channel` int(11) DEFAULT NULL,
  `yz_channel` int(11) DEFAULT NULL,
  `out_channel` varchar(255) DEFAULT NULL,
  `channel_result` varchar(255) DEFAULT NULL,
  `yz_shop_id` varchar(255) DEFAULT NULL,
  `yz_shop_no` varchar(255) DEFAULT NULL,
  `out_shop` varchar(255) DEFAULT NULL,
  `shop_result` varchar(255) DEFAULT NULL,
  `yz_address` varchar(255) DEFAULT NULL,
  `out_address` varchar(255) DEFAULT NULL,
  `address_result` varchar(255) DEFAULT NULL,
  `yz_create_time` varchar(255) DEFAULT NULL,
  `out_create_time` varchar(255) DEFAULT NULL,
  `create_time_result` varchar(255) DEFAULT NULL,
  `yz_level` varchar(255) DEFAULT NULL,
  `out_level` varchar(255) DEFAULT NULL,
  `level_result` varchar(255) DEFAULT NULL,
  `yz_point` int(11) DEFAULT NULL,
  `out_point` int(11) DEFAULT NULL,
  `point_result` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_mobile` (`app_id`,`mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `third_party_member_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `member_id` varchar(255) DEFAULT NULL,
  `out_member_detail` text,
  `status` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_mobile` (`app_id`,`mobile`),
  KEY `idx_app_member_id` (`app_id`,`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `youzan_member_detail` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kdt_id` bigint(20) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `yz_open_id` varchar(255) DEFAULT NULL,
  `youzan_member_detail` text,
  `status` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_app_mobile` (`app_id`,`mobile`),
  KEY `idx_app_yz_open_id` (`app_id`,`yz_open_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;